# Generated by Django 6.0.1 on 2026-02-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['token'], name='cloth_email_token_cff41f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['expires_at'], name='cloth_email_expires_6f5998_idx'),
        ),
    ]
