# Generated by Django 6.0.1 on 2026-02-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_emailverification_cloth_email_token_cff41f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('yookassa', 'ЮKassa (Онлайн)'), ('cash', 'Наличные при получении')], default='yookassa', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
