# Generated by Django 6.0.1 on 2026-02-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Изображение'),
        ),
    ]
